import type { Metadata } from "next";
import "./globals.css";
import { WalletProvider } from "./contexts/WalletContext";
import PayPalProvider from "./components/PayPalProvider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Mythic Muses",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          httpEquiv="Permissions-Policy"
          content="geolocation=(self 'https://www.paypal.com'), microphone=(), camera=()"
        />
      </head>
      <body className="antialiased">
        <WalletProvider>
          <PayPalProvider>
            {children}
            <Toaster
              position="top-right"
              toastOptions={{
                duration: 4000,
                style: {
                  background: "#1a1a1a",
                  color: "#fff",
                  border: "1px solid #333",
                },
                success: {
                  iconTheme: {
                    primary: "#10b981",
                    secondary: "#fff",
                  },
                },
                error: {
                  iconTheme: {
                    primary: "#ef4444",
                    secondary: "#fff",
                  },
                },
              }}
            />
          </PayPalProvider>
        </WalletProvider>
      </body>
    </html>
  );
}
